
import { Code, Smartphone, Palette, ShieldCheck, Rocket, BrainCircuit, Landmark, SwatchBook, ImageIcon, Gamepad2, Users } from 'lucide-react';

export const services = [
    {
        slug: "web-development",
        template: "default",
        icon: Code,
        title: "Web Development",
        description: "Building modern, responsive, and scalable web applications.",
        longDescription: "We craft beautiful and functional web experiences, from simple landing pages to complex enterprise applications. Our team uses the latest technologies to ensure your project is fast, secure, and ready to scale.",
        image: "https://placehold.co/800x600.png",
        imageHint: "web development code",
        imageUrl: "https://placehold.co/1920x1080.png",
        points: [
            { title: "Frontend", description: "Utilizing modern frameworks like React and Next.js to build dynamic and responsive user interfaces." },
            { title: "Backend", description: "Developing robust server-side applications with Node.js, Python, and other powerful technologies." },
            { title: "Databases", description: "Managing and modeling data with both SQL (PostgreSQL) and NoSQL (MongoDB) databases." },
            { title: "DevOps", description: "Streamlining deployment and scaling with Docker, Kubernetes, and CI/CD pipelines." },
        ],
        chartData: [
            { year: 2014, 'Projects': 5 },
            { year: 2015, 'Projects': 8 },
            { year: 2016, 'Projects': 13 },
            { year: 2017, 'Projects': 18 },
            { year: 2018, 'Projects': 25 },
            { year: 2019, 'Projects': 40 },
            { year: 2020, 'Projects': 60 },
            { year: 2021, 'Projects': 85 },
            { year: 2022, 'Projects': 110 },
            { year: 2023, 'Projects': 140 },
        ],
    },
    {
        slug: "mobile-app-development",
        template: "default",
        icon: Smartphone,
        title: "Mobile App Development",
        description: "Native and cross-platform mobile apps that deliver seamless user experiences on iOS and Android.",
        longDescription: "From concept to launch, we create compelling mobile applications that connect with users. Whether you need a native iOS or Android app or a cross-platform solution, we deliver performance, usability, and style.",
        image: "https://placehold.co/800x600.png",
        imageHint: "mobile app design",
        imageUrl: "https://placehold.co/1920x1081.png",
        points: [
            { title: "iOS Development", description: "Building high-performance, native applications for the Apple ecosystem using Swift and SwiftUI." },
            { title: "Android Development", description: "Creating versatile and reliable native Android apps using Kotlin and Java." },
            { title: "Cross-Platform", description: "Efficiently building for both platforms with frameworks like React Native and Flutter." },
            { title: "UI/UX for Mobile", description: "Designing intuitive and engaging interfaces optimized for mobile devices." },
        ],
         chartData: [
            { year: 2014, 'Projects': 2 },
            { year: 2015, 'Projects': 4 },
            { year: 2016, 'Projects': 6 },
            { year: 2017, 'Projects': 8 },
            { year: 2018, 'Projects': 10 },
            { year: 2019, 'Projects': 22 },
            { year: 2020, 'Projects': 35 },
            { year: 2021, 'Projects': 50 },
            { year: 2022, 'Projects': 70 },
            { year: 2023, 'Projects': 95 },
        ],
    },
     {
        slug: "custom-software",
        template: "default",
        icon: Code,
        title: "Custom Software Development",
        description: "Bespoke software solutions tailored to your unique business needs.",
        longDescription: "We specialize in creating custom software solutions that solve specific business challenges. Our team works closely with you to understand your requirements and deliver a product that is perfectly aligned with your goals.",
        image: "https://placehold.co/800x600.png",
        imageHint: "custom software planning",
        imageUrl: "https://placehold.co/1920x1082.png",
        points: [
            { title: "Requirement Analysis", description: "Deeply understanding your business processes to define the right features." },
            { title: "Scalable Architecture", description: "Designing systems that can grow with your business." },
            { title: "Third-Party Integrations", description: "Connecting your software with other tools and services you use." },
            { title: "Ongoing Support", description: "Providing maintenance and updates to keep your software running smoothly." },
        ],
        chartData: [
            { year: 2014, 'Projects': 1 },
            { year: 2015, 'Projects': 2 },
            { year: 2016, 'Projects': 3 },
            { year: 2017, 'Projects': 4 },
            { year: 2018, 'Projects': 5 },
            { year: 2019, 'Projects': 15 },
            { year: 2020, 'Projects': 28 },
            { year: 2021, 'Projects': 42 },
            { year: 2022, 'Projects': 60 },
            { year: 2023, 'Projects': 80 },
        ],
    },
    {
        slug: "game-development",
        template: "default",
        icon: Code,
        title: "Game Development",
        description: "Creating immersive and engaging games for various platforms.",
        longDescription: "We bring your game ideas to life, from concept art to final release. Our team has experience with a wide range of game genres and technologies, ensuring a fun and polished final product.",
        image: "https://placehold.co/800x600.png",
        imageHint: "game development screen",
        imageUrl: "https://placehold.co/1920x1083.png",
        points: [
            { title: 'Game Design', description: 'Creating core mechanics, levels, and stories that are fun and engaging.' },
            { title: '2D & 3D Art', description: 'Producing stunning visuals, characters, and environments.' },
            { title: 'Unity & Unreal Engine', description: 'Using industry-standard game engines to build high-performance games.' },
            { title: 'Multiplayer Integration', description: 'Building real-time multiplayer functionality for your games.' },
        ],
        chartData: [
            { year: 2014, 'Projects': 0 },
            { year: 2015, 'Projects': 1 },
            { year: 2016, 'Projects': 1 },
            { year: 2017, 'Projects': 2 },
            { year: 2018, 'Projects': 2 },
            { year: 2019, 'Projects': 5 },
            { year: 2020, 'Projects': 10 },
            { year: 2021, 'Projects': 18 },
            { year: 2022, 'Projects': 25 },
            { year: 2023, 'Projects': 35 },
        ],
    },
    {
        slug: "business-automation",
        template: "default",
        icon: Rocket,
        title: "Business Automation",
        description: "Streamlining your business processes with intelligent automation.",
        longDescription: "We help you automate repetitive tasks and streamline your workflows, freeing up your team to focus on what matters most. Our solutions are designed to improve efficiency, reduce errors, and drive growth.",
        image: "https://placehold.co/800x600.png",
        imageHint: "business process flowchart",
        imageUrl: "https://placehold.co/1920x1084.png",
        points: [
            { title: "Workflow Analysis", description: "Identifying opportunities for automation within your existing processes." },
            { title: "RPA", description: "Implementing Robotic Process Automation to handle repetitive digital tasks." },
            { title: "Custom Scripts", description: "Writing custom scripts to automate specific tasks and integrations." },
            { title: "AI-Powered Automation", description: "Using AI to handle more complex decision-making and automation." },
        ],
        chartData: [
            { year: 2014, 'Projects': 1 },
            { year: 2015, 'Projects': 2 },
            { year: 2016, 'Projects': 4 },
            { year: 2017, 'Projects': 6 },
            { year: 2018, 'Projects': 8 },
            { year: 2019, 'Projects': 18 },
            { year: 2020, 'Projects': 30 },
            { year: 2021, 'Projects': 45 },
            { year: 2022, 'Projects': 65 },
            { year: 2023, 'Projects': 90 },
        ],
    },
    {
        slug: "ui-ux-design",
        template: "default",
        icon: Palette,
        title: "UI/UX Design",
        description: "Intuitive and beautiful user interfaces that are a joy to use, enhancing user engagement and satisfaction.",
        longDescription: "Our design process is centered around the user. We conduct in-depth research to understand your audience, creating wireframes, prototypes, and final designs that are not only visually stunning but also highly functional and intuitive.",
        image: "https://placehold.co/800x600.png",
        imageHint: "ui design tools",
        imageUrl: "https://placehold.co/1920x1082.png",
        points: [
            { title: "User Research", description: "Gathering insights through interviews, surveys, and analysis to inform design decisions." },
            { title: "Wireframing & Prototyping", description: "Creating interactive blueprints to define layout, structure, and user flow." },
            { title: "Visual Design", description: "Crafting a compelling visual identity with typography, color theory, and iconography." },
            { title: "Usability Testing", description: "Validating designs with real users to ensure an optimal user experience." },
        ],
        chartData: [
            { year: 2014, 'Projects': 10 },
            { year: 2015, 'Projects': 15 },
            { year: 2016, 'Projects': 20 },
            { year: 2017, 'Projects': 25 },
            { year: 2018, 'Projects': 30 },
            { year: 2019, 'Projects': 50 },
            { year: 2020, 'Projects': 75 },
            { year: 2021, 'Projects': 100 },
            { year: 2022, 'Projects': 130 },
            { year: 2023, 'Projects': 160 },
        ],
    },
    {
        slug: "qa-testing",
        template: "default",
        icon: ShieldCheck,
        title: "QA & Testing",
        description: "Rigorous quality assurance processes to ensure your software is reliable, secure, and bug-free.",
        longDescription: "Quality is at the core of our development process. Our dedicated QA team employs a combination of manual and automated testing strategies to ensure your application is secure, reliable, and performs flawlessly.",
        image: "https://placehold.co/800x600.png",
        imageHint: "testing checklist",
        imageUrl: "https://placehold.co/1920x1083.png",
        points: [
            { title: "Manual Testing", description: "Executing detailed test cases to identify bugs and usability issues from a user's perspective." },
            { title: "Automated Testing", description: "Developing scripts to automate repetitive tests, ensuring consistency and efficiency." },
            { title: "Performance Testing", description: "Analyzing application speed, scalability, and stability under various load conditions." },
            { title: "Security Testing", description: "Identifying and mitigating vulnerabilities to protect your application and user data." },
        ],
         chartData: [
            { year: 2014, 'Projects': 20 },
            { year: 2015, 'Projects': 25 },
            { year: 2016, 'Projects': 35 },
            { year: 2017, 'Projects': 42 },
            { year: 2018, 'Projects': 50 },
            { year: 2019, 'Projects': 80 },
            { year: 2020, 'Projects': 120 },
            { year: 2021, 'Projects': 160 },
            { year: 2022, 'Projects': 200 },
            { year: 2023, 'Projects': 250 },
        ],
    },
    {
        slug: "devops",
        template: "default",
        icon: Rocket,
        title: "DevOps",
        description: "Streamlining development and operations to deliver high-quality software faster and more reliably.",
        longDescription: "We implement DevOps best practices to bridge the gap between development and operations. Our goal is to automate your infrastructure, streamline workflows, and foster a culture of collaboration to accelerate your release cycles.",
        image: "https://placehold.co/800x600.png",
        imageHint: "devops pipeline",
        imageUrl: "https://placehold.co/1920x1084.png",
        points: [
            { title: "CI/CD", description: "Implementing Continuous Integration and Continuous Delivery pipelines for faster, reliable releases." },
            { title: "Infrastructure as Code", description: "Managing and provisioning infrastructure through code for consistency and scalability." },
            { title: "Monitoring & Logging", description: "Setting up robust monitoring and logging to ensure system health and quick troubleshooting." },
            { title: "Cloud Services", description: "Leveraging AWS, Google Cloud, and Azure to build scalable and resilient infrastructure." },
        ],
         chartData: [
            { year: 2014, 'Projects': 3 },
            { year: 2015, 'Projects': 6 },
            { year: 2016, 'Projects': 10 },
            { year: 2017, 'Projects': 12 },
            { year: 2018, 'Projects': 15 },
            { year: 2019, 'Projects': 30 },
            { year: 2020, 'Projects': 50 },
            { year: 2021, 'Projects': 75 },
            { year: 2022, 'Projects': 100 },
            { year: 2023, 'Projects': 130 },
        ],
    },
    {
        slug: "ai-ml-solutions",
        template: "default",
        icon: BrainCircuit,
        title: "AI & ML Solutions",
        description: "Integrating artificial intelligence and machine learning to build intelligent, data-driven applications.",
        longDescription: "Unlock the power of your data with our AI and Machine Learning solutions. We help you build intelligent systems that can automate processes, predict outcomes, and provide valuable insights to drive your business forward.",
        image: "https://placehold.co/800x600.png",
        imageHint: "neural network",
        imageUrl: "https://placehold.co/1920x1085.png",
        points: [
            { title: "Data Analysis", description: "Processing and analyzing large datasets to uncover patterns and trends." },
            { title: "Predictive Modeling", description: "Building models that forecast future events and behaviors with high accuracy." },
            { title: "Natural Language Processing", description: "Enabling applications to understand and process human language." },
            { title: "Computer Vision", description: "Developing systems that can 'see' and interpret visual information from images and videos." },
        ],
        chartData: [
            { year: 2014, 'Projects': 1 },
            { year: 2015, 'Projects': 2 },
            { year: 2016, 'Projects': 2 },
            { year: 2017, 'Projects': 3 },
            { year: 2018, 'Projects': 3 },
            { year: 2019, 'Projects': 8 },
            { year: 2020, 'Projects': 15 },
            { year: 2021, 'Projects': 25 },
            { year: 2022, 'Projects': 40 },
            { year: 2023, 'Projects': 60 },
        ],
    },
    {
        slug: 'e-governance',
        template: 'egovernance',
        icon: Landmark,
        title: 'e-Governance Solutions',
        description: 'Pioneering Digital Transformation in Public Services Through Advanced e-Governance Solutions.',
        longDescription: 'We develop and implement cutting-edge digital platforms designed to streamline government operations, enhance the delivery of public services, and foster greater transparency and citizen engagement across all sectors.',
        image: 'https://placehold.co/800x600.png',
        imageHint: 'government building',
        imageUrl: 'https://placehold.co/1920x1086.png',
        points: [
            { title: 'Public Service Portals', description: 'Developing citizen-centric portals for easy access to government services and information.' },
            { title: 'Digital Document Management', description: 'Implementing secure systems for managing official records and reducing paperwork.' },
            { title: 'Online Licensing & Permits', description: 'Streamlining the application and approval processes for various licenses and permits.' },
            { title: 'Smart City Solutions', description: 'Integrating technology to improve urban services like traffic management and public safety.' },
        ],
        stats: [
            { name: 'Projects Delivered', value: '150+' },
            { name: 'Citizen Satisfaction', value: '95%' },
            { name: 'Efficiency Increase', value: '40%' },
        ],
        chartData: [
            { year: 2014, 'Projects': 5, 'Adoption Rate': 30 },
            { year: 2015, 'Projects': 7, 'Adoption Rate': 40 },
            { year: 2016, 'Projects': 10, 'Adoption Rate': 45 },
            { year: 2017, 'Projects': 12, 'Adoption Rate': 50 },
            { year: 2018, 'Projects': 12, 'Adoption Rate': 50 },
            { year: 2019, 'Projects': 19, 'Adoption Rate': 65 },
            { year: 2020, 'Projects': 32, 'Adoption Rate': 75 },
            { year: 2021, 'Projects': 45, 'Adoption Rate': 80 },
            { year: 2022, 'Projects': 58, 'Adoption Rate': 85 },
            { year: 2023, 'Projects': 73, 'Adoption Rate': 92 },
        ],
        differentiators: [
            { title: 'Deep Domain Expertise', description: 'Understanding of public sector workflows and compliance requirements.' },
            { title: 'Scalable & Secure Architecture', description: 'Building robust systems that can handle nationwide scale and protect sensitive data.' },
            { title: 'User-Centric Design', description: 'Prioritizing accessibility and ease-of-use for all citizens, regardless of technical skill.' },
            { title: 'Long-Term Partnership', description: 'Providing ongoing support and maintenance to ensure the longevity of our solutions.' }
        ]
    }
];
